@echo off

:: This script generates two files - a plugins_custom_dirs.dat file which is included in custom_dirs.dat,
:: and a plugins_env.dat file which is included in NX_env.dat.
:: Each run of the script will regenerate the files.
:: Run this script after making changes to the contents of Plugins.

echo #  This file is automatically generated based on the folders found in ${NXCUSTOM_PLUGINS}.> plugins_custom_dirs.dat
echo #  Any modifications made will be overwritten then next time update_plugins.bat is run.>> plugins_custom_dirs.dat
echo: >> plugins_custom_dirs.dat

echo #  This file is automatically generated based on the folders found in ${NXCUSTOM_PLUGINS}.> plugins_env.dat
echo #  Any modifications made will be overwritten then next time update_plugins.bat is run.>> plugins_env.dat
echo: >> plugins_env.dat

setlocal enabledelayedexpansion
for /d %%a in (*) do (
	set __a=%%~na
	if "!__a:~0,1!" neq "_" (
		echo ${NXCUSTOM_PLUGINS}\!__a!>> plugins_custom_dirs.dat
		for /f "usebackq delims=" %%b in (`dir /b "!__a!"`) do (
			set __b=%%b
			if "!__b:~-7!" == "env.dat" (
				echo #include ${NXCUSTOM_PLUGINS}\!__a!\!__b!>> plugins_env.dat			
			)
		)
	)
)
setlocal disabledelayedexpansion